export const SET_ALERT = 'SET_ALERT'
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'
export const GET_CONFIG = 'GET_CONFIG'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const SET_BANNER_IMAGES = 'SET_BANNER_IMAGES'
export const GET_CART_ITEMS = 'GET_CART_ITEMS'
export const ADD_TO_CART = 'ADD_TO_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const UPDATE_COUNT = 'UPDATE_COUNT'
export const DELETE_ITEM_CART = 'DELETE_ITEM_CART'
export const ADD_LOCATION = 'ADD_LOCATION'
export const ADD_HOMESCREEN_LOCATION = 'ADD_HOMESCREEN_LOCATION'
export const DELETE_LOCATION = 'DELETE_LOCATION'
export const CLEAR_REDUX_PERSIST = 'CLEAR_REDUX_PERSIST'
export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const GET_ALL_USER_ADDRESSES = 'GET_ALL_USER_ADDRESSES'
export const GETCREDIT_TRANSACTIONS = 'GETCREDIT_TRANSACTIONS'





