export const SET_ALERT = 'SET_ALERT'
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'
export const GET_CONFIG = 'GET_CONFIG'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const ADD_TO_CART = 'ADD_TO_CART'
export const CLEAR_CART = 'CLEAR_CART'
export const UPDATE_COUNT = 'UPDATE_COUNT'
export const DELETE_ITEM_CART = 'DELETE_ITEM_CART'
export const ADD_LOCATION = 'ADD_LOCATION'
export const DELETE_LOCATION = 'DELETE_LOCATION'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const SAVE_USER_DETAILS = 'SAVE_USER_DETAILS'



